name: Keep Streamlit Awake

on:
  schedule:
    - cron: "*/15 * * * *"  # every 15 minutes (UTC)
  workflow_dispatch: {}      # allow manual run

permissions:
  contents: read

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit app
        run: |
          URL="${{ vars.STREAMLIT_URL }}"
          if [ -z "$URL" ]; then
            echo "STREAMLIT_URL repo variable not set."
            exit 1
          fi
          echo "Pinging $URL"
          # Try up to 3 times; add a cache-busting param
          for i in 1 2 3; do
            CODE=$(curl -L -s -o /dev/null -w "%{http_code}" --max-time 20 "$URL?keepalive=$(date +%s)")
            echo "Attempt $i -> HTTP $CODE"
            if [ "$CODE" = "200" ] || [ "$CODE" = "302" ]; then
              exit 0
            fi
            sleep 5
          done
          # Don’t fail the workflow if it’s still waking
          echo "Non-200 after retries; continuing (likely still waking)."
          exit 0
